CREATE TABLE AGENCIA(
    Id_Agencia NUMBER(5),
    nombre VARCHAR2(50),
    pais VARCHAR2(50),
    AUTOR_EXAMEN VARCHAR(150),
    CONSTRAINT PK_AGENCIA PRIMARY KEY (Id_Agencia),
    CONSTRAINT NN_AGENCIA_NOMBRE CHECK (nombre IS NOT NULL),
    CONSTRAINT NN_AGENCIA_PAIS CHECK (pais IS NOT NULL),
    CONSTRAINT NN_AGENCIA_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL)
);

CREATE TABLE SATELITE(
    Id_Satelite NUMBER(5),
    nombre VARCHAR2(9),
    orbita VARCHAR2(15),
    peso NUMBER(15),
    coste NUMBER(15),
    activo BOOLEAN(15),
    AUTOR_EXAMEN VARCHAR(150),
    Id_Agencia NUMBER(5),
    Id_Detalle NUMBER(5),
    CONSTRAINT PK_SATELITE PRIMARY KEY (Id_Satelite),
    CONSTRAINT NN_SATELITE_NOMBRE CHECK (nombre IS NOT NULL),
    CONSTRAINT NN_SATELITE_ORBITA CHECK (orbita IS NOT NULL),
    CONSTRAINT NN_SATELITE_PESO CHECK (peso IS NOT NULL),
    CONSTRAINT NN_SATELITE_COSTE CHECK (coste IS NOT NULL),
    CONSTRAINT NN_SATELITE_ACTIVO CHECK (activo IS NOT NULL),
    CONSTRAINT NN_SATELITE_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL),
    CONSTRAINT FK_SATELITE_ID_AGENCIA FOREIGN KEY (Id_Agencia) REFERENCES AGENCIA,
    CONSTRAINT FK_SATELITE_ID_DETALLESATELITE FOREIGN KEY (Id_DetalleSatelite) REFERENCES DETALLESATELITE
);

INSERT INTO SATELITE VALUES (1, 'Maria Antonieta', 'A', 1000000, 900000001, TRUE , 'ANDRES_ARA_DAM2',1,1);
INSERT INTO SATELITE VALUES (2, 'El Surcador de las 7 orbias', 'B', 2000000, 900000002, TRUE , 'ANDRES_ARA_DAM2',2,2);
INSERT INTO SATELITE VALUES (3, 'Orbitinator', 'C', 3000000, 900000003, TRUE , 'ANDRES_ARA_DAM2',3,3);
INSERT INTO SATELITE VALUES (4, 'COHETECHAN', 'D', 4000000, 900000004, TRUE , 'ANDRES_ARA_DAM2',4,4);
INSERT INTO SATELITE VALUES (5, 'AGATO 15', 'E', 5000000, 900000005, TRUE , 'ANDRES_ARA_DAM2',5,5);

CREATE TABLE DETALLESATELITE(
    Id_DetalleSatelite NUMBER(5),
    velocidadMaxima NUMBER(9),
    combustible NUMBER(15),
    vidaUtil NUMBER(15),
    AUTOR_EXAMEN VARCHAR(150),
    Id_Satelite NUMBER(5),
    CONSTRAINT PK_DETALLESATELITE PRIMARY KEY (Id_DetalleSatelite),
    CONSTRAINT NN_DETALLESATELITE_VELOCIDADMAXIMA CHECK (velocidadMaxima IS NOT NULL),
    CONSTRAINT NN_DETALLESATELITE_COMBUSTIBLE CHECK (combustible IS NOT NULL),
    CONSTRAINT NN_DETALLESATELITE_VIDAUTIL CHECK (vidaUtil IS NOT NULL),
    CONSTRAINT NN_DETALLESATELITE_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL),
    CONSTRAINT FK_DETALLESATELITE_ID_SATELITE FOREIGN KEY (Id_Satelite) REFERENCES SATELITE
);

INSERT INTO DETALLESATELITE VALUES (1, 5001, 301, 201, 'ANDRES_ARA_DAM2',1);
INSERT INTO DETALLESATELITE VALUES (2, 5002, 302, 202, 'ANDRES_ARA_DAM2',2);
INSERT INTO DETALLESATELITE VALUES (3, 5003, 303, 203, 'ANDRES_ARA_DAM2',3);
INSERT INTO DETALLESATELITE VALUES (4, 5004, 304, 204, 'ANDRES_ARA_DAM2',4);
INSERT INTO DETALLESATELITE VALUES (5, 5005, 305, 205, 'ANDRES_ARA_DAM2',5);

