CREATE TABLE AGENCIA(
    Id_Agencia INTEGER(5),
    nombre VARCHAR2(50),
    pais VARCHAR2(50),
    AUTOR_EXAMEN VARCHAR(150),
    CONSTRAINT PK_AGENCIA PRIMARY KEY (Id_Agencia),
    CONSTRAINT NN_AGENCIA_NOMBRE CHECK (nombre IS NOT NULL),
    CONSTRAINT NN_AGENCIA_PAIS CHECK (pais IS NOT NULL),
    CONSTRAINT NN_AGENCIA_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL)
);

CREATE TABLE SATELITE(
    Id_Satelite INTEGER(5),
    nombre VARCHAR2(9),
    orbita VARCHAR2(15),
    peso INTEGER(15),
    coste INTEGER(15),
    activo BOOLEAN(15),
    AUTOR_EXAMEN VARCHAR(150),
    Id_Agencia INTEGER(5),
    Id_Detalle INTEGER(5),
    CONSTRAINT PK_SATELITE PRIMARY KEY (Id_Satelite),
    CONSTRAINT NN_SATELITE_NOMBRE CHECK (nombre IS NOT NULL),
    CONSTRAINT NN_SATELITE_ORBITA CHECK (orbita IS NOT NULL),
    CONSTRAINT NN_SATELITE_PESO CHECK (peso IS NOT NULL),
    CONSTRAINT NN_SATELITE_COSTE CHECK (coste IS NOT NULL),
    CONSTRAINT NN_SATELITE_ACTIVO CHECK (activo IS NOT NULL),
    CONSTRAINT NN_SATELITE_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL),
    CONSTRAINT FK_SATELITE_ID_AGENCIA FOREIGN KEY (Id_Agencia) REFERENCES AGENCIA,
    CONSTRAINT FK_SATELITE_ID_DETALLESATELITE FOREIGN KEY (Id_DetalleSatelite) REFERENCES DETALLESATELITE
);

CREATE TABLE DETALLESATELITE(
    Id_DetalleSatelite INTEGER(5),
    velocidadMaxima INTEGER(9),
    combustible INTEGER(15),
    vidaUtil INTEGER(15),
    AUTOR_EXAMEN VARCHAR(150),
    Id_Satelite INTEGER(5),
    CONSTRAINT PK_DETALLESATELITE PRIMARY KEY (Id_DetalleSatelite),
    CONSTRAINT NN_DETALLESATELITE_VELOCIDADMAXIMA CHECK (velocidadMaxima IS NOT NULL),
    CONSTRAINT NN_DETALLESATELITE_COMBUSTIBLE CHECK (combustible IS NOT NULL),
    CONSTRAINT NN_DETALLESATELITE_VIDAUTIL CHECK (vidaUtil IS NOT NULL),
    CONSTRAINT NN_DETALLESATELITE_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL),
    CONSTRAINT FK_DETALLESATELITE_ID_SATELITE FOREIGN KEY (Id_Satelite) REFERENCES SATELITE
);