INSERT INTO AGENCIA VALUES (1, 'GATOS ESPACIALES', 'ESPANIA', 'ANDRES_ARA_DAM2');
INSERT INTO AGENCIA VALUES (2, 'DRUNKEN GATOS', 'NORUEGA', 'ANDRES_ARA_DAM2');
INSERT INTO AGENCIA VALUES (3, 'RUSKY GATOS', 'RUSIA', 'ANDRES_ARA_DAM2');
INSERT INTO AGENCIA VALUES (4, 'GATOCHANES', 'JAPON', 'ANDRES_ARA_DAM2');
INSERT INTO AGENCIA VALUES (5, 'GATILLOS', 'AMERICA', 'ANDRES_ARA_DAM2');